apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mvp

commonLabels:
  app: tst


resources:
  - tst.yml


patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: tst
      namespace: mvp
      version: v1
    path: auto-inject.yml
