apiVersion: v1
kind: ConfigMap
metadata:
  name: centrifugo-config
  namespace: mvp
data:
  config.yaml: |
    v3_use_offset: true
    token_hmac_secret_key: s0DUdTauvlfLlYIGLQCjoWF8DksuudUM
    api_key: my_api_key
    admin_password: password
    admin_secret: secret
    log_level: debug
    admin: true
    port: 8000
    engine: memory
    websocket_compression: true
    client_insecure: true
    health: true
    debug: true
    sockjs_disable: true
    api_disable: true
    admin_handler_prefix: /ws/admin
    websocket_handler_prefix: /ws
