apiVersion: apps/v1
kind: Deployment

metadata:
  name: centrifugo
  namespace: mvp
  labels:
    app: centrifugo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: centrifugo

  template:
    metadata:
      labels:
        app: centrifugo

    spec:
      containers:
        - image: gcr.io/maap-test-292714/cfgo:dev
          imagePullPolicy: Always
          name: centrifugo
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:

  name: centrifugo
  namespace: mvp

  labels:
    app: centrifugo

spec:
  ports:
    - port: 8585
      targetPort: 8000

  selector:
    app: centrifugo
  type: ClusterIP
