apiVersion: v1
kind: ConfigMap
metadata:
  name: centrifugo-config
  namespace: mvp
data:
  config.yaml: |
    v3_use_offset: true
    token_hmac_secret_key: s0DUdTauvlfLlYIGLQCjoWF8DksuudUM
    api_key: my_api_key
    admin_password: password
    admin_secret: secret
    log_level: debug
    admin: true
    engine: memory
    websocket_compression: false
    client_anonymous: true
    client_insecure: true
    gomaxprocs:1
    health: true
    debug: false
    sockjs_disable: true
    api_disable: false
    websocket_handler_prefix: /hub
#    admin_handler_prefix: /admin

