apiVersion: apps/v1
kind: Deployment

metadata:
  name: centrifugo
  namespace: mvp
  labels:
    app: centrifugo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: centrifugo

  template:
    metadata:
      labels:
        app: centrifugo

    spec:
      containers:
        - image: centrifugo/centrifugo
          imagePullPolicy: Always
          name: centrifugo
          command: [ 'centrifugo' ]
          args: [ "-c", "config.json", "--port",  "8000",  "--admin" ]
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:

  name: centrifugo
  namespace: mvp

  labels:
    app: centrifugo

spec:
  ports:
    - port: 8000
      targetPort: 8000

  selector:
    app: centrifugo
  type: LoadBalancer
